name: Cypress Tests

on:[push]

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: yarn install

      -name: Run E2E teste
       run: yarn cypress run
